# Generated by Django 6.0.1 on 2026-01-30 14:01

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('frontend', 'Frontend Technologies'), ('backend', 'Backend Technologies'), ('database', 'Databases'), ('tools', 'Tools & Frameworks'), ('cloud', 'Cloud & DevOps'), ('other', 'Other Skills')], max_length=20)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon (e.g., fab fa-python)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on main portfolio page')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['category', '-proficiency', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Challenges faced during development'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image URLs'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on main portfolio page'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_personal',
            field=models.BooleanField(default=True, help_text='Personal project vs client work'),
        ),
        migrations.AddField(
            model_name='project',
            name='learned',
            field=models.TextField(blank=True, help_text='What you learned from this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Live demo URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='my_role',
            field=models.CharField(blank=True, help_text='Your role in the project', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile App'), ('desktop', 'Desktop Application'), ('api', 'API/Backend'), ('ml', 'Machine Learning'), ('data', 'Data Analysis'), ('game', 'Game Development'), ('other', 'Other')], default='web', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='Project description', help_text='Brief description for cards', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='default-project', help_text='URL-friendly version of title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('development', 'In Development'), ('completed', 'Completed'), ('maintenance', 'Maintenance'), ('archived', 'Archived')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of team members'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Detailed project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in this project', to='portfolio.skill'),
        ),
    ]
