# Generated by Django 6.0.1 on 2026-02-07 22:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about_skill_alter_project_options_remove_project_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('resume', 'Resume/CV'), ('portfolio', 'Portfolio PDF'), ('certificate', 'Certificate'), ('other', 'Other Document')], max_length=20)),
                ('download_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Detected location', max_length=100)),
            ],
            options={
                'verbose_name': 'Download Tracking',
                'verbose_name_plural': 'Download Tracking',
                'ordering': ['-download_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('reddit', 'Reddit'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=280)),
                ('content', models.TextField(help_text='Post content/caption')),
                ('hashtags', models.CharField(blank=True, help_text='Comma-separated hashtags', max_length=500)),
                ('media_url', models.URLField(blank=True, help_text='Image/video URL', null=True)),
                ('post_url', models.URLField(blank=True, help_text='URL of published post', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person giving testimonial', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(help_text='Job title or position', max_length=150)),
                ('company', models.CharField(blank=True, help_text='Company or organization', max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('testimonial_type', models.CharField(choices=[('client', 'Client Review'), ('colleague', 'Colleague Recommendation'), ('supervisor', 'Supervisor Recommendation'), ('peer', 'Peer Review'), ('other', 'Other')], default='client', max_length=20)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('title', models.CharField(help_text='Short title for the testimonial', max_length=200)),
                ('content', models.TextField(help_text='The actual testimonial text')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('website_url', models.URLField(blank=True, help_text='Personal/company website')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on main portfolio page')),
                ('is_approved', models.BooleanField(default=True, help_text='Approved for display')),
                ('date_given', models.DateField(help_text='Date the testimonial was given')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Associated project if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-date_given', '-created_at'],
            },
        ),
    ]
