# Generated by Django 6.0.1 on 2026-02-07 23:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_downloadtracking_socialmediapost_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for category badge', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon (e.g., fas fa-code)', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='School, university, or institution name', max_length=200)),
                ('degree_type', models.CharField(choices=[('highschool', 'High School Diploma'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate/PhD'), ('certificate', 'Certificate Program'), ('bootcamp', 'Coding Bootcamp'), ('online', 'Online Course'), ('other', 'Other')], max_length=20)),
                ('program_name', models.CharField(help_text='Degree title or program name', max_length=200)),
                ('field_of_study', models.CharField(blank=True, help_text='Major, specialization, or field', max_length=150)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('deferred', 'Deferred'), ('dropped', 'Dropped')], default='completed', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Expected or actual graduation date', null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Grade Point Average', max_digits=3, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details, achievements, or coursework')),
                ('location', models.CharField(blank=True, help_text='City, State/Country', max_length=150)),
                ('website_url', models.URLField(blank=True, help_text='Institution website')),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently on main pages')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(help_text='Brief description for previews', max_length=300)),
                ('content', models.TextField(help_text='Full blog post content (supports Markdown)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('content_type', models.CharField(choices=[('tutorial', 'Tutorial'), ('case_study', 'Case Study'), ('opinion', 'Opinion Piece'), ('technical', 'Technical Article'), ('industry', 'Industry Insights'), ('personal', 'Personal Experience'), ('news', 'News & Updates'), ('other', 'Other')], default='technical', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, help_text='SEO optimized title', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for SEO', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured post on blog homepage')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.blogcategory')),
                ('related_projects', models.ManyToManyField(blank=True, help_text='Related portfolio projects', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Certification name', max_length=200)),
                ('issuing_organization', models.CharField(help_text='Organization that issued the certificate', max_length=200)),
                ('certification_type', models.CharField(choices=[('technical', 'Technical Certification'), ('professional', 'Professional Certification'), ('vendor', 'Vendor Certification'), ('industry', 'Industry Certification'), ('academic', 'Academic Certification'), ('online', 'Online Course Certificate'), ('other', 'Other')], default='technical', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('in_progress', 'In Progress')], default='active', max_length=20)),
                ('credential_id', models.CharField(blank=True, help_text='Certificate or badge ID', max_length=100)),
                ('issue_date', models.DateField(help_text='Date certification was earned')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiration date if applicable', null=True)),
                ('description', models.TextField(blank=True, help_text='Skills or knowledge gained')),
                ('verification_url', models.URLField(blank=True, help_text='Link to verify credential')),
                ('badge_image', models.ImageField(blank=True, help_text='Digital badge or certificate image', null=True, upload_to='certifications/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on main portfolio page')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills_gained', models.ManyToManyField(blank=True, help_text='Skills related to this certification', to='portfolio.skill')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Position title', max_length=150)),
                ('company_name', models.CharField(help_text='Company or organization name', max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('volunteer', 'Volunteer'), ('other', 'Other')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('current', 'Current Position'), ('completed', 'Past Position')], default='current', max_length=20)),
                ('start_date', models.DateField(help_text='Employment start date')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current position', null=True)),
                ('location', models.CharField(help_text="City, State/Country or 'Remote'", max_length=150)),
                ('company_description', models.TextField(blank=True, help_text='Brief company overview')),
                ('job_description', models.TextField(help_text='Role overview and key responsibilities')),
                ('key_achievements', models.TextField(blank=True, help_text='Major accomplishments and achievements')),
                ('company_website', models.URLField(blank=True, help_text='Company website URL')),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='companies/')),
                ('reference_contact', models.CharField(blank=True, help_text='Reference contact information', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on main portfolio page')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies_used', models.ManyToManyField(blank=True, help_text='Technologies and skills used', to='portfolio.skill')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
                'ordering': ['-start_date', '-end_date'],
            },
        ),
    ]
