# Generated by Django 6.0.1 on 2026-02-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blogcategory_education_blogpost_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='title',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, help_text='Short title for the testimonial', max_length=200),
        ),
    ]
