# Generated by Django 6.0.1 on 2026-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, help_text='Full blog post content (supports Markdown)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Brief description for previews', max_length=300),
        ),
    ]
