# Generated by Django 5.2.9 on 2026-02-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_blogpost_content_alter_blogpost_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Brief description for previews (optional)', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, help_text='Blog post title (auto-generated if empty)', max_length=200),
        ),
    ]
