# Generated by Django 5.2.9 on 2026-05-27 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_blogpost_excerpt_alter_blogpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('conference', 'Conference'), ('meetup', 'Meetup'), ('workshop', 'Workshop'), ('hackathon', 'Hackathon'), ('seminar', 'Seminar'), ('networking', 'Networking'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(help_text='Date the event took place')),
                ('location', models.CharField(blank=True, help_text='Venue or city', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('frontend', 'Frontend Technologies'), ('backend', 'Backend Technologies'), ('data', 'Data & Analytics'), ('tools', 'Tools & Frameworks'), ('cloud', 'Cloud & DevOps'), ('productivity', 'Productivity & Office Tools'), ('other', 'Other Skills')], max_length=20),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.event')),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
