# Generated by Django 5.2.15 on 2026-08-27 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_add_event_eventphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(help_text='Topic this post belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Blog post title', max_length=200),
        ),
    ]
