# Generated by Django 5.2.15 on 2026-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_drop_social_auth_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', models.OrderBy(models.Case(models.When(proficiency='expert', then=models.Value(4)), models.When(proficiency='advanced', then=models.Value(3)), models.When(proficiency='intermediate', then=models.Value(2)), models.When(proficiency='beginner', then=models.Value(1)), default=models.Value(0), output_field=models.IntegerField()), descending=True), 'name']},
        ),
    ]
